In [1]:
import numpy as np

- Генерация массивов со случайными значениями

In [3]:
# 1-мерный массив случайных целых значений

arr_0 = np.random.randint(5, size=10)
arr_0

array([0, 3, 4, 4, 2, 4, 3, 1, 3, 4])

In [8]:
# np.random.randint(-10, 10, size=10)
np.random.randint(-10, 10, 10)

array([ 1, -4,  4, -6,  1, -4,  5, -7,  7,  3])

In [6]:
np.random.randint(-100, 100, size=(3,5))

array([[ 13,  90, -53, -59, -27],
       [-13,  97,  83,  34,  -2],
       [ 11,  75,  76,  40,  81]])

In [11]:
# 2-мерный массив случайных значений с плавающей точкой в диапазоне от 0 до 1
np.random.random((3, 3))

array([[0.712941  , 0.97434123, 0.7397347 ],
       [0.16929292, 0.80887107, 0.66201827],
       [0.1699018 , 0.03328072, 0.19313266]])

In [12]:
# массив случайных чисел с плавающей точкой
#  из нормального (гауссова) распределения

np.random.randn(3, 4)

array([[ 0.29845689,  1.26035945, -0.60400032, -0.51445247],
       [ 0.47219317, -0.87378865, -0.45101858,  0.62814075],
       [ 0.33093364, -3.19105683, -0.9171475 ,  0.24160255]])

- Атрибуты

In [13]:
arr_0 = np.random.randint(5, size=10)
arr_0

array([1, 1, 3, 0, 0, 3, 3, 3, 1, 3])

In [14]:
# форма массива
arr_0.shape

(10,)

In [15]:
# тип данных
arr_0.dtype

dtype('int32')

In [16]:
# мерность массива
arr_0.ndim

1

In [17]:
# объем занимаемой памяти (в байтах)
arr_0.nbytes

40

- Методы

In [18]:
# конвертация типов данных
arr_0.astype("float16")

array([1., 1., 3., 0., 0., 3., 3., 3., 1., 3.], dtype=float16)

In [19]:
arr_1 = np.random.randint(100, size=(3,5))
arr_1

array([[34, 60,  0, 79, 82],
       [57, 76, 60, 90, 98],
       [98, 27, 51, 58, 20]])

In [21]:
# транспонирование
# arr_1.transpose()
arr_1.T

array([[34, 57, 98],
       [60, 76, 27],
       [ 0, 60, 51],
       [79, 90, 58],
       [82, 98, 20]])

- Индексация

In [22]:
arr_2 = np.random.randint(10, size=(3,4))
arr_2

array([[0, 1, 0, 2],
       [5, 2, 5, 2],
       [7, 8, 5, 0]])

In [23]:
# прямая индексация
arr_2[1]

array([5, 2, 5, 2])

In [24]:
# обратная индексация
arr_2[-1]

array([7, 8, 5, 0])

In [27]:
# синтаксис списков и кортежей
# arr_2[2][3]

# синтаксис numpy
arr_2[2, 3]

0